# Generated by Django 4.0.5 on 2022-06-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('surname', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaaripCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maaripCategory', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Maarip Category',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', models.TextField()),
                ('subtitle', models.TextField()),
            ],
            options={
                'verbose_name': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='Maarip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('maarip_image', models.ImageField(blank=True, null=True, upload_to='maarip_image/')),
                ('maarip_Video', models.FileField(blank=True, null=True, upload_to='maarip_Video/')),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('publicatetime', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('category', models.ManyToManyField(to='maarip.maaripcategory')),
            ],
            options={
                'verbose_name': 'Maarip',
                'verbose_name_plural': 'Maarip',
                'ordering': ['-publicatetime'],
            },
        ),
    ]
