# Generated by Django 4.0.5 on 2022-06-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aileCategory', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Aile Category',
            },
        ),
        migrations.CreateModel(
            name='Aile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('aile_image', models.ImageField(blank=True, null=True, upload_to='aile_image/')),
                ('aile_Video', models.FileField(blank=True, null=True, upload_to='aile_Video/')),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('publicatetime', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aile_Category', to='aile.ailecategory')),
            ],
            options={
                'verbose_name': 'Aile',
                'verbose_name_plural': 'Aile',
                'ordering': ['-publicatetime'],
            },
        ),
    ]
