# Generated by Django 4.0.5 on 2022-06-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuhCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruhCategory', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Ruh Category',
            },
        ),
        migrations.CreateModel(
            name='Ruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('solution1', models.CharField(blank=True, max_length=200, null=True)),
                ('solution2', models.CharField(blank=True, max_length=200, null=True)),
                ('solution3', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.TextField()),
                ('ruh_image1', models.ImageField(blank=True, null=True, upload_to='ruh_image/')),
                ('ruh_image2', models.ImageField(blank=True, null=True, upload_to='ruh_image/')),
                ('ruh_Video', models.FileField(blank=True, null=True, upload_to='ruh_video/')),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('publicatetime', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruh.ruhcategory')),
            ],
            options={
                'verbose_name': 'Ruh',
                'verbose_name_plural': 'Ruh',
                'ordering': ['-publicatetime'],
            },
        ),
        migrations.CreateModel(
            name='FAQS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.TextField()),
                ('ruh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ruh.ruh')),
            ],
            options={
                'verbose_name_plural': 'Question&Answer',
            },
        ),
    ]
